### ISSUE TITLE
Support Enhanced Ecommerce

### ISSUE THREAD

**Issue by sawyerh** [woothemes/woocommerce-google-analytics-integration#17]
Reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

This would replace ecommerce.js and give users [way more info](https://support.google.com/analytics/answer/6014857) on the ecommerce user flow.

**Comment by mikejolley** [comment]
This is an enhancement @BFTrick wanted. Care to explain a little more?

**Comment by BFTrick** [comment]
With enchanced e-commerce we should support:

* Impression data
* Product data (when added to cart and when checking out)
* Action data (purchase + refunds)
* Actions 

We should still offer the option for legacy e-commerce reporting in case someone hasn't upgraded their account yet.

## Future 

* Promotion data
