### ISSUE TITLE
PlugIn Not Working On My Site

### ISSUE THREAD

**Issue by asparrow** [woothemes/woocommerce-google-analytics-integration#38]
Since I installed this on my site all my previous analytic information is GONE and it is currently not collecting any data. I have flat line 0 across the board for 24 hours now.
![screen shot 2014-12-03 at 4 02 53 pm](https://cloud.githubusercontent.com/assets/8306541/5288787/173cfdf6-7b06-11e4-9943-6aebd77d48de.png)
 It does not even show real time users. I need help ASAP! I'm just hoping that my previous analytics is not gone. I can see the tracking ID in the source code so it does appear to be there, but nothing on the data collection side including real time.

junieblove.co

**Comment by mikejolley** [comment]
#41
