### ISSUE TITLE
No ecommerce conversions after upgrade to WC 2.2.10

### ISSUE THREAD

**Issue by itecedor** [woothemes/woocommerce-google-analytics-integration#41]
This plugin was working beautifully for us for months on [gothamquilts.com](gothamquilts.com), but after I upgraded the site to WooCommerce 2.2.10, no ecommerce conversions are showing in GA anymore. All other aspects of GA appear to be working correctly, but the ecommerce data doesn't seem to be going over.

**Comment by zjwhitehead** [comment]
I guess they arent supporting this plugin anymore?

**Comment by optiguy** [comment]
Free plugin - No support as they said.

**Comment by mikejolley** [comment]
We'll check to ensure it's still working in 2.3/2.4.

**Comment by claudiosmweb** [comment]
I'm using this integration with WooCommerce 2.3 and works really fine.

**Comment by mikejolley** [comment]
ok. Lets just make sure what we have is robust as possible and works with all default core gateways.

**Comment by justinshreve** [comment]
I tested the integration with all of the core gateways (+mijireh) and I confirm that I see data inside GA.
It also looks like what we have for the standard eCommerce tracking is good. More robust tracking can come when #17 is handled. I'm closing this since things look good.
