### ISSUE TITLE
Track analytics settings if WC tracking is enabled

### ISSUE THREAD

**Issue by justinshreve** [woothemes/woocommerce-google-analytics-integration#46]
[See the suggestion here](https://github.com/woothemes/woocommerce-google-analytics-integration/pull/45#issuecomment-116728066):

> If someone has opted into WC tracking maybe we can pass a few more points of data? Ex. what type of analytics they're using (universal or legacy; enhanced ecommerce or regular, etc). Then down the road if we see all new installs using universal we can make that the default and hide the option.

I think tracking both those settings makes sense and can help us clean up the UI in the future depending on actual usage.

**Comment by mikejolley** [comment]
This is handled in the class: https://github.com/woothemes/woocommerce/blob/ecac3fba413afeaa7dc7c6ddd7d49cf4fc7e7b45/includes/class-wc-tracker.php

@kloon Do you have any recommendations for this? There are no filters, so would you just want these option values hardcoded in (if they exist, or if the plugin is detected)?

**Comment by kloon** [comment]
You can hook into woocommerce_tracker_data filter and add your option via that, it will then automatically get picked up on our end and be added to the list of data being tracked for the site.
