### ISSUE TITLE
Group "Enhanced eCommerce" options

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce-google-analytics-integration#51]
Rather than show these checkboxes with the description:

"Requires Enhanced eCommerce."

I think it would be good to instead hide that description and use JS to only reveal the options when enhanced ecommerce is checked. Less options = Less scary settings pages.

**Comment by lkraav** [comment]
Not sure if this is worth a new issue, but Enhanced E-commerce should be hidden if "Universal Analytics" is unchecked. As far as I can tell based on [link](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce), these states are mutually exclusive.

**Comment by justinshreve** [comment]
Good point. I opened up a new issue for it and will work on that tomorrow. Thanks!
