### ISSUE TITLE
Add tracking code option

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce-google-analytics-integration#64]
We have this option in the settings

![](http://cld.wthms.co/1jk70/3qdBXjmI+)

It does not make sense to me.
In `class-wc-google-analytics.php` check the method `tracking_code_display()`. It won't add any code if that option is disabled, so why do we say that you don't need to enable that if you are already using a 3rd-party analytics plugin?

Our code won't be added if that option is disabled.

**Comment by justinshreve** [comment]
1.4 makes this setting clearer already with some updated descriptions, but basically that setting tells the GA plugin if we should show tracking on pages that are not eCommerce pages. So if you already have a plugin that tracks views, you can leave this off and our plugin will only handle eCommerce data. We still load our tracking code in other instances (is_checkout, etc).

**Comment by SiR-DanieL** [comment]
@justinshreve I may be wrong, but I think that if that option is enabled then also the ecommerce code is not printed.

**Comment by justinshreve** [comment]
In stable:

[Line 128](https://github.com/woothemes/woocommerce-google-analytics-integration/blob/1.3.0/includes/class-wc-google-analytics.php#L127) displays the eCommerce code if its the order received page and "Add eCommerce tracking code to the thankyou page" is enabled" so although the variable names are similar, one is standard tracking and one is eCommerce tracking.


[Line 138](https://github.com/woothemes/woocommerce-google-analytics-integration/blob/1.3.0/includes/class-wc-google-analytics.php#L138) shows the "standard" code if eCommerce code was not previously shown and the standard option is enabled.

In master (1.4) things are about the same except we show the eCommerce one in more places then the "thank you" page.

**Comment by justinshreve** [comment]
BTW - For the "thank you" page, the code will only display once per user -- since it tracks an order being finished. So if you refresh or revisit the page later you won't see the tracking code.
