### ISSUE TITLE
The plugin breaks my pages due to a malformed javascript when I activate Enhanced eCommerce

### ISSUE THREAD

**Issue by rmarpozo** [woothemes/woocommerce-google-analytics-integration#74]
This javascript breaks my pages

ga( 'ec:addProduct', {
  'id': '939',
  'name': 'Batamo',
  'category': 'Juegos de mesa/Juguetes',
  'position': 
});

The position attribute is not well formed and that breaks the whole page.

Why is the position attribute empty?

Thanks

**Comment by sboerrigter** [comment]
You can get around this bug by disabling "Product Impressions from Listing Pages" and "Product Clicks from Listing Pages". I know this is not the best solution, but it worked for me.
